// <auto-generated />
using System;
using Internacion;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Internacion.Migrations
{
    [DbContext(typeof(InternacContext))]
    [Migration("20190516202715_InternacionDB")]
    partial class InternacionDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Internacion.Internac_paciente", b =>
                {
                    b.Property<int>("Id_internacion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha_ingreso");

                    b.Property<int>("Id_expediente");

                    b.Property<int>("Id_personal");

                    b.Property<string>("Imp_diagnostica");

                    b.Property<string>("Tratamiento");

                    b.HasKey("Id_internacion");

                    b.ToTable("InternacionPacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
